name = "Hey Its Laneyys SMP"
author = "DarthJake"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6177bf03b5b8025fdadb16a3fe7319d685ab92bf423ee3234af2326ffaa7861e"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
