name = "Hey Its Laneyys SMP"
author = "DarthJake"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "345d300d6089f7979ef149e46eb988a81396ec2485a48769a31f5868d349e0f0"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
