name = "Hey Its Laneyys SMP"
author = "DarthJake"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e6b17124e734d882bfa70a69b0be678af6c649fca29643067a189ce0468b1e3"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
